# Generated by Django 5.0.14 on 2026-08-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Set once the user has confirmed their username and real name.",
            ),
        ),
    ]
