# Generated by Django 5.0.14 on 2026-07-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="1-based presentation order."
                    ),
                ),
                (
                    "shuffled_options",
                    models.JSONField(
                        help_text="Options re-shuffled and re-lettered A, B, C... for this attempt."
                    ),
                ),
                (
                    "correct_label",
                    models.CharField(
                        help_text="Re-lettered correct label for this attempt.",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBankItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_hint",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Original position in the uploaded file (display only).",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        help_text='List of {"label": "A", "text": "..."} dicts, in bank order.'
                    ),
                ),
                ("correct_label", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order_hint", "id"],
            },
        ),
        migrations.CreateModel(
            name="AttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_label",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="quizzes.attemptquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attemptquestion",
            name="bank_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="quizzes.questionbankitem",
            ),
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="How long a student has once they start the quiz."
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        help_text="Minimum percentage (0-100) correct required to pass."
                    ),
                ),
                (
                    "quiz_length",
                    models.PositiveIntegerField(
                        help_text="Number of questions sampled from the bank per attempt."
                    ),
                ),
                ("allow_retake_on_fail", models.BooleanField(default=False)),
                ("show_class_average", models.BooleanField(default=False)),
                ("opening_time", models.DateTimeField()),
                ("closing_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionbankitem",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_items",
                to="quizzes.quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline_at",
                    models.DateTimeField(
                        help_text="Authoritative deadline: min(started_at + duration, closing_time), computed once at attempt creation."
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("auto_submitted", models.BooleanField(default=False)),
                (
                    "score_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attemptquestion",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quizattempt",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["status", "opening_time", "closing_time"],
                name="quizzes_qui_status_53482e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["quiz", "student", "started_at"],
                name="quizzes_qui_quiz_id_467f84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(
                fields=["student", "submitted_at"],
                name="quizzes_qui_student_8298c5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attemptquestion",
            constraint=models.UniqueConstraint(
                fields=("attempt", "position"), name="unique_attempt_position"
            ),
        ),
    ]
