# Generated by Django 5.0.14 on 2026-07-23 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptquestion",
            name="bank_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.questionbankitem",
            ),
        ),
    ]
