# Generated by Django 5.0.14 on 2026-08-05 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0002_alter_attemptquestion_bank_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only used when assignment is 'Specific students'.",
                related_name="assigned_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="assignment",
            field=models.CharField(
                choices=[("all", "All students"), ("specific", "Specific students")],
                default="all",
                max_length=10,
            ),
        ),
    ]
