# Generated by Django 5.0.14 on 2026-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_quiz_assigned_students_quiz_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_length",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of questions sampled from the bank per attempt. Leave blank to include every question in the bank on every attempt.",
                null=True,
            ),
        ),
    ]
