# Generated by Django 5.0.14 on 2026-08-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0004_alter_quiz_quiz_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="expiration_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When the quiz (and its question bank, attempts, and results) is permanently deleted. This is separate from the closing time -- students are locked out at closing time, but the quiz and its data stick around until it expires. Leave blank to keep it indefinitely.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="closing_time",
            field=models.DateTimeField(
                help_text="When the quiz stops accepting new attempts from students."
            ),
        ),
    ]
