# Generated by Django 5.0.14 on 2026-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_quiz_expiration_time_alter_quiz_closing_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="allow_retake_on_fail",
            new_name="allow_retake",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="allow_retake",
            field=models.BooleanField(
                default=False,
                help_text="Whether a student may retake this quiz after finishing it, whether they passed or failed.",
            ),
        ),
    ]
