# Generated by Django 5.0.14 on 2026-08-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0006_remove_quiz_allow_retake_on_fail_quiz_allow_retake"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="retake_granted_by_teacher",
            field=models.BooleanField(
                default=False,
                help_text="A teacher-granted exception letting this specific student retake the quiz once even though it doesn't allow retakes generally. Only applies while this is the student's latest attempt.",
            ),
        ),
    ]
