# Generated by Django 5.0.14 on 2026-08-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0007_quizattempt_retake_granted_by_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="show_answers_after_close",
            field=models.BooleanField(
                default=False,
                help_text="Once the quiz's closing time has passed, let students review their own answers alongside the correct answers on their results page.",
            ),
        ),
    ]
